# headers and icon 
title: Soumya Sarkar
info: JRF @ IIT Ropar
icon-pic: assets/img/conference_dp.jpg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
